---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-backend
  labels:
    app: catalog-backend
    fdk.service: catalog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      fdk.service: catalog-backend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: catalog-backend
        fdk.service: catalog-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: catalog-backend
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+UseZGC -XX:MaxRAMPercentage=80.0"
            - name: POSTGRESQL_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: HOST
            - name: POSTGRESQL_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: PORT
            - name: POSTGRESQL_DB
              valueFrom:
                secretKeyRef:
                  name: catalog-backend
                  key: POSTGRESQL_DB
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: catalog-backend
                  key: POSTGRESQL_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: catalog-backend
                  key: POSTGRESQL_PASSWORD
            - name: KEYCLOAK_OIDC_ISSUER
              valueFrom:
                secretKeyRef:
                  name: keycloak
                  key: KEYCLOAK_OIDC_ISSUER
            - name: CORS_ORIGIN_PATTERNS
              valueFrom:
                secretKeyRef:
                  name: catalog-backend
                  key: CORS_ORIGIN_PATTERNS
            - name: ADMIN_API_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: ADMIN_API_BASE_URI
            - name: CATALOG_IDENTIFIER_HOST
              valueFrom:
                secretKeyRef:
                  name: resource-identificators
                  key: CATALOG_HOST
            - name: INFORMATION_MODEL_IDENTIFIER_HOST
              valueFrom:
                secretKeyRef:
                  name: resource-identificators
                  key: INFORMATION_MODEL_HOST
            - name: CATALOG_BACKEND_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: CATALOG_BACKEND_BASE_URI
            - name: ORGANIZATION_CATALOG_BASE_URI
              valueFrom:
                secretKeyRef:
                  name: commonurl
                  key: ORGANIZATION_CATALOG_BASE_URI
          image: catalog-backend
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 5
          resources:
            requests:
              cpu: 20m
              memory: 1500Mi
            limits:
              memory: 1500Mi
