---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - catalog-backend-deployment.yaml
  - catalog-backend-service.yaml
images:
  - name: catalog-backend
    newName: ghcr.io/informasjonsforvaltning/catalog-backend
    newTag: $(GIT_COMMIT_SHA)
